zones:
  area_atendimento_fila:
  - - 280
    - 199
  - - 93
    - 209
  - - 160
    - 353
  - - 566
    - 355
  - - 707
    - 278
  - - 686
    - 246
  - - 370
    - 324
  ponto_pagamento:
  - - 303
    - 85
  - - 64
    - 104
  - - 88
    - 207
  - - 318
    - 156
  zona_funcionario_caixa:
  - - 337
    - 94
  - - 362
    - 157
  - - 471
    - 160
  - - 461
    - 85
lines: {}
